### PR TITLE
Create Discuss

### PR DESCRIPTION
**Pull request by globalkitty**

### CODE REVIEW

**Review by globalkitty — COMMENTED** [review]
ok?

**Comment by globalkitty** [comment]
Hello

**Comment by penguin011** [comment]
Thank you very much for your question.

**Comment by anochkasky** [comment]
Hello
I am anochka.
I think so.

**Review by anochkasky — COMMENTED** [review]
understand

**Comment by penguin011** [comment]
Thank you all

**Comment by penguin011** [comment]
This project is not easy as you think.

**Pull request merged**
